### ISSUE TITLE
Enter the password manually every time？

### ISSUE THREAD

**Issue by wisinfun** [frank-m/alfred-rdp-workflow#5]
![CleanShot 2021-07-22 at 12 45 41](https://user-images.githubusercontent.com/41355260/126591123-aa1ae503-d9a3-47c6-8b27-2a32b8dfa852.png)
Remember the password in time, it's still the same

**Comment by frank-m** [comment]
Hi,

I’m afraid this is not possible. What happens is not that the bookmark gets opened directly, but the details get read of the bookmark and opened as a totally new connection each time.

As such it is not possible to save the password anywhere. The RDP client does not support opening bookmarks directly via het cli.

Thanks for using the workflow.

Frank

**Comment by wisinfun** [comment]
> Hi,
> 
> I’m afraid this is not possible. What happens is not that the bookmark gets opened directly, but the details get read of the bookmark and opened as a totally new connection each time.
> 
> As such it is not possible to save the password anywhere. The RDP client does not support opening bookmarks directly via het cli.
> 
> Thanks for using the workflow.
> 
> Frank

Thank you very much for your answer
